# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('airport', models.CharField(max_length=5)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MiddlePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_port', models.CharField(max_length=5)),
                ('arrival_port', models.CharField(max_length=5)),
                ('middle_port', models.CharField(max_length=5)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_type', models.CharField(default='Normal', max_length=25, null=True)),
                ('sit_class', models.CharField(default='Trevaler', max_length=20)),
                ('carrier', models.CharField(default='Aiur', max_length=5)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_port', models.ForeignKey(db_column='arrival_port', on_delete=django.db.models.deletion.CASCADE, related_name='arr_code', related_query_name='arrival', to='search.Airport', to_field='code')),
                ('departure_port', models.ForeignKey(db_column='departure_port', on_delete=django.db.models.deletion.CASCADE, related_name='dep_code', related_query_name='depart', to='search.Airport', to_field='code')),
            ],
        ),
    ]
